### ISSUE TITLE
delete this repo

### ISSUE THREAD

**Issue by SaraOgaz** [spacetelescope/astronomy-resources#2]
@sosey, is it okay if I delete this repo?  Not sure if there was anything in here you wanted to save.

**Comment by sosey** [comment]
I'm fine with that. This was just a test repo we created to try and orgainze tutorials and user questions.

**Comment by embray** [comment]
RIP
It was a great idea at the time but never really took off or received the time/funding/support from management needed to make it go (or maybe it did but in another form?)

**Comment by sosey** [comment]
yah, it never did. Though they keep talking about how we should have a common place to store tutorials, etc... :woman_shrugging:

**Comment by pllim** [comment]
Well, between Astropy Tutorials, STAK, and CSI, I think we will get them covered? :crossed_fingers:

**Comment by sosey** [comment]
and https://github.com/spacetelescope/jwst-pipeline-notebooks

**Comment by SaraOgaz** [comment]
Okay, thanks. Closing issue!
